# GET https://bank-of-seamless.herokuapp.com/api/v1/balance

# GET http://localhost:2400/api/v1/user/user

# POST http://localhost:2400/api/v1/register-user
# Content-Type: application/json

# {
# "name": "shafran",
# "email": "shafran@ieee.org",
# "contact_no" : "0771713701",
# "password" : "123456789999"
# }

POST http://localhost:2400/api/v1/user/login
Content-Type: application/json

{
"email": "shafran@ieee.org",
"password" : "123456789999"
}



# POST http://localhost:2400/api/v1/add-user-work-exp
# Content-Type: application/json

# {
# "user_id": "61fd2d48e28e4c3a9d133977",
# "job_title": "TEST_!23",
# "company": "Deliveegate",
# "industry": "hello",
# "date_started" : "2022/02/04",
# "is_present": true
# }


# POST http://localhost:2400/api/v1/add-user-skill
# Content-Type: application/json

# {
# "user_id": "61fd2d48e28e4c3a9d133977",
# "skill_name": "Node Js"
# }

# POST http://localhost:2400/api/v1/add-user-education
# Content-Type: application/json

# {
# "user_id": "61fd2d48e28e4c3a9d133977",
# "edu_level": "Masters",
# "edu_feild" : "Software Engineering",
# "school":"Plymouth University",
# "date_started" : "2022/02/04",
# "is_present" : true
# }

# POST http://localhost:2400/api/v1/admin/register-company-admin
# Content-Type: application/json

# {
# "company_name": "Honey Pvt Ltd",
# "email": "hone@jo.com",
# "password": "123456789999",
# "country": "United Kindom",
# "industry": "Hospitality"
# }

# POST http://localhost:2400/api/v1/admin/create-job
# Content-Type: application/json

# {
# "company_id": "61fe376b8f4b831d9ff9b25c",
# "job_title": "test Enginner",
# "job_description": "Test tetstst tetetettete lorum ipsum",
# "is_accepting": true
# }

# PUT http://localhost:2400/api/v1/admin/edit-job?job_id=61fe549935cf1ac18b21ec5a
# Content-Type: application/json

# {
# "company_id": "61fe376b8f4b831d9ff9b25c",
# "job_title": "[Updated 666]Back end Enginner",
# "job_description": "Test tetstst tetetettete lorum ipsum",
# "is_accepting": true
# }

# GET http://localhost:2400/api/v1/user/get-all-jobs


# GET http://localhost:2400/api/v1/admin/get-jobs-by-company-id?company_id=61fe376b8f4b831d9ff9b25c

# POST http://localhost:2400/api/v1/user/apply-job
# Content-Type: application/json

# {
#  "user_id": "61fd2d48e28e4c3a9d133977",
# "job_id": "61fe549935cf1ac18b21ec5a"
# }

# GET http://localhost:2400/api/v1/user/get-user-basic-details?user_id=61fd2d48e28e4c3a9d133977
# GET http://localhost:2400/api/v1/user/get-user-applied-jobs?user_id=61fd2d48e28e4c3a9d133977